FROM python:3.7-alpine

RUN apk add --update alpine-sdk glib glib-dev linux-headers jq bash

RUN mkdir /app

WORKDIR /app

RUN pip install yq
RUN pip install wf-shoe-sensor

COPY scripts/run-honeycomb.sh .

CMD ["sh", "run-honeycomb.sh"]

